import type { ThemeConfig } from '../theme/types';
import {
  defaultTypography,
  defaultSpacing,
  defaultRadius,
  defaultShadows,
} from '../theme/defaults';

// ---------------------------------------------------------------------------
// 1. Warm Orange
// ---------------------------------------------------------------------------
export const presetWarmOrange: ThemeConfig = {
  name: 'Warm Orange',
  colors: {
    light: {
      primary: '#FF8C6B',
      primaryDark: '#E06B4A',
      primaryLight: '#FFB199',
      secondary: '#FFD54F',
      secondaryDark: '#C8A415',
      accent: '#FF6E40',
      background: '#FFFAF7',
      backgroundSecondary: '#FFF3ED',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#2D1B14',
      textSecondary: '#6D4C41',
      textMuted: '#A1887F',
      textOnPrimary: '#FFFFFF',
      border: '#FFCCBC',
      divider: '#FFE0D0',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#FF8C6B',
      primaryDark: '#E06B4A',
      primaryLight: '#FFB199',
      secondary: '#FFD54F',
      secondaryDark: '#C8A415',
      accent: '#FF6E40',
      background: '#1A1210',
      backgroundSecondary: '#2D1F1A',
      surface: '#3E2C24',
      surfaceElevated: '#4E3A32',
      text: '#FFF3ED',
      textSecondary: '#FFCCBC',
      textMuted: '#A1887F',
      textOnPrimary: '#FFFFFF',
      border: '#5D4037',
      divider: '#4E342E',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 2. Monochrome
// ---------------------------------------------------------------------------
export const presetMonochrome: ThemeConfig = {
  name: 'Monochrome',
  colors: {
    light: {
      primary: '#212121',
      primaryDark: '#000000',
      primaryLight: '#484848',
      secondary: '#757575',
      secondaryDark: '#494949',
      accent: '#000000',
      background: '#FAFAFA',
      backgroundSecondary: '#F5F5F5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#212121',
      textSecondary: '#616161',
      textMuted: '#9E9E9E',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      divider: '#EEEEEE',
      error: '#B71C1C',
      success: '#2E7D32',
      warning: '#E65100',
      info: '#0D47A1',
    },
    dark: {
      primary: '#FAFAFA',
      primaryDark: '#E0E0E0',
      primaryLight: '#FFFFFF',
      secondary: '#BDBDBD',
      secondaryDark: '#8D8D8D',
      accent: '#FFFFFF',
      background: '#121212',
      backgroundSecondary: '#1E1E1E',
      surface: '#2C2C2C',
      surfaceElevated: '#383838',
      text: '#FAFAFA',
      textSecondary: '#BDBDBD',
      textMuted: '#757575',
      textOnPrimary: '#121212',
      border: '#424242',
      divider: '#333333',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 3. Ocean Blue
// ---------------------------------------------------------------------------
export const presetOceanBlue: ThemeConfig = {
  name: 'Ocean Blue',
  colors: {
    light: {
      primary: '#2196F3',
      primaryDark: '#1565C0',
      primaryLight: '#64B5F6',
      secondary: '#00BCD4',
      secondaryDark: '#00838F',
      accent: '#0288D1',
      background: '#F5F9FF',
      backgroundSecondary: '#E3F2FD',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#0D2137',
      textSecondary: '#37474F',
      textMuted: '#90A4AE',
      textOnPrimary: '#FFFFFF',
      border: '#BBDEFB',
      divider: '#E1F0FF',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#0288D1',
    },
    dark: {
      primary: '#42A5F5',
      primaryDark: '#1E88E5',
      primaryLight: '#90CAF9',
      secondary: '#26C6DA',
      secondaryDark: '#00ACC1',
      accent: '#29B6F6',
      background: '#0A1929',
      backgroundSecondary: '#112240',
      surface: '#1A2F4A',
      surfaceElevated: '#243B55',
      text: '#E3F2FD',
      textSecondary: '#90CAF9',
      textMuted: '#546E7A',
      textOnPrimary: '#FFFFFF',
      border: '#1E3A5F',
      divider: '#162D4A',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#29B6F6',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 4. Forest Green
// ---------------------------------------------------------------------------
export const presetForestGreen: ThemeConfig = {
  name: 'Forest Green',
  colors: {
    light: {
      primary: '#4CAF50',
      primaryDark: '#2E7D32',
      primaryLight: '#81C784',
      secondary: '#8BC34A',
      secondaryDark: '#558B2F',
      accent: '#009688',
      background: '#F5FBF5',
      backgroundSecondary: '#E8F5E9',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#1B3A1B',
      textSecondary: '#33691E',
      textMuted: '#A5D6A7',
      textOnPrimary: '#FFFFFF',
      border: '#C8E6C9',
      divider: '#E0F2E0',
      error: '#D32F2F',
      success: '#2E7D32',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#66BB6A',
      primaryDark: '#43A047',
      primaryLight: '#A5D6A7',
      secondary: '#9CCC65',
      secondaryDark: '#7CB342',
      accent: '#26A69A',
      background: '#0D1F0D',
      backgroundSecondary: '#1A331A',
      surface: '#243824',
      surfaceElevated: '#2E4A2E',
      text: '#E8F5E9',
      textSecondary: '#A5D6A7',
      textMuted: '#558B2F',
      textOnPrimary: '#FFFFFF',
      border: '#2E5E2E',
      divider: '#1E3D1E',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 5. Sunset Purple
// ---------------------------------------------------------------------------
export const presetSunsetPurple: ThemeConfig = {
  name: 'Sunset Purple',
  colors: {
    light: {
      primary: '#9C27B0',
      primaryDark: '#7B1FA2',
      primaryLight: '#CE93D8',
      secondary: '#E91E63',
      secondaryDark: '#AD1457',
      accent: '#AB47BC',
      background: '#FDF5FF',
      backgroundSecondary: '#F3E5F5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#2A0E30',
      textSecondary: '#4A148C',
      textMuted: '#BA68C8',
      textOnPrimary: '#FFFFFF',
      border: '#E1BEE7',
      divider: '#F0DEF5',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#CE93D8',
      primaryDark: '#AB47BC',
      primaryLight: '#E1BEE7',
      secondary: '#F48FB1',
      secondaryDark: '#EC407A',
      accent: '#BA68C8',
      background: '#1A0E1F',
      backgroundSecondary: '#2D1636',
      surface: '#3E2046',
      surfaceElevated: '#4E2A58',
      text: '#F3E5F5',
      textSecondary: '#CE93D8',
      textMuted: '#7B1FA2',
      textOnPrimary: '#FFFFFF',
      border: '#4A1F5E',
      divider: '#381850',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 6. Sakura Pink
// ---------------------------------------------------------------------------
export const presetSakuraPink: ThemeConfig = {
  name: 'Sakura Pink',
  colors: {
    light: {
      primary: '#F48FB1',
      primaryDark: '#EC407A',
      primaryLight: '#F8BBD0',
      secondary: '#CE93D8',
      secondaryDark: '#AB47BC',
      accent: '#FF80AB',
      background: '#FFFAFC',
      backgroundSecondary: '#FFF0F5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#33141E',
      textSecondary: '#880E4F',
      textMuted: '#F48FB1',
      textOnPrimary: '#FFFFFF',
      border: '#F8BBD0',
      divider: '#FDDDE6',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#F48FB1',
      primaryDark: '#EC407A',
      primaryLight: '#F8BBD0',
      secondary: '#CE93D8',
      secondaryDark: '#AB47BC',
      accent: '#FF80AB',
      background: '#1F0F15',
      backgroundSecondary: '#331825',
      surface: '#462232',
      surfaceElevated: '#592C40',
      text: '#FFF0F5',
      textSecondary: '#F8BBD0',
      textMuted: '#AD1457',
      textOnPrimary: '#FFFFFF',
      border: '#6E2D48',
      divider: '#4D1E33',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 7. Midnight Navy
// ---------------------------------------------------------------------------
export const presetMidnightNavy: ThemeConfig = {
  name: 'Midnight Navy',
  colors: {
    light: {
      primary: '#1A237E',
      primaryDark: '#0D1257',
      primaryLight: '#534BAE',
      secondary: '#283593',
      secondaryDark: '#1A237E',
      accent: '#3F51B5',
      background: '#F5F6FF',
      backgroundSecondary: '#E8EAF6',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#0D0F33',
      textSecondary: '#1A237E',
      textMuted: '#9FA8DA',
      textOnPrimary: '#FFFFFF',
      border: '#C5CAE9',
      divider: '#E0E3F5',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#7986CB',
      primaryDark: '#5C6BC0',
      primaryLight: '#9FA8DA',
      secondary: '#8C9EFF',
      secondaryDark: '#536DFE',
      accent: '#7C4DFF',
      background: '#0A0D2E',
      backgroundSecondary: '#131641',
      surface: '#1C2054',
      surfaceElevated: '#252A66',
      text: '#E8EAF6',
      textSecondary: '#9FA8DA',
      textMuted: '#3F51B5',
      textOnPrimary: '#FFFFFF',
      border: '#283593',
      divider: '#1A237E',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 8. Earth Brown
// ---------------------------------------------------------------------------
export const presetEarthBrown: ThemeConfig = {
  name: 'Earth Brown',
  colors: {
    light: {
      primary: '#795548',
      primaryDark: '#5D4037',
      primaryLight: '#A1887F',
      secondary: '#8D6E63',
      secondaryDark: '#6D4C41',
      accent: '#FF8A65',
      background: '#FDFAF8',
      backgroundSecondary: '#EFEBE9',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#2B1B14',
      textSecondary: '#4E342E',
      textMuted: '#BCAAA4',
      textOnPrimary: '#FFFFFF',
      border: '#D7CCC8',
      divider: '#EFEBE9',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#A1887F',
      primaryDark: '#8D6E63',
      primaryLight: '#BCAAA4',
      secondary: '#BCAAA4',
      secondaryDark: '#A1887F',
      accent: '#FFAB91',
      background: '#1A1210',
      backgroundSecondary: '#2B1F1A',
      surface: '#3E2E26',
      surfaceElevated: '#4E3C32',
      text: '#EFEBE9',
      textSecondary: '#BCAAA4',
      textMuted: '#6D4C41',
      textOnPrimary: '#FFFFFF',
      border: '#5D4037',
      divider: '#4E342E',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 9. Neon Cyber
// ---------------------------------------------------------------------------
export const presetNeonCyber: ThemeConfig = {
  name: 'Neon Cyber',
  colors: {
    light: {
      primary: '#00E5FF',
      primaryDark: '#00B8D4',
      primaryLight: '#80F0FF',
      secondary: '#76FF03',
      secondaryDark: '#64DD17',
      accent: '#D500F9',
      background: '#F0FDFF',
      backgroundSecondary: '#E0F7FA',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#0A2A33',
      textSecondary: '#006064',
      textMuted: '#80DEEA',
      textOnPrimary: '#003340',
      border: '#B2EBF2',
      divider: '#E0F7FA',
      error: '#FF1744',
      success: '#00E676',
      warning: '#FF9100',
      info: '#00B0FF',
    },
    dark: {
      primary: '#00E5FF',
      primaryDark: '#00B8D4',
      primaryLight: '#80F0FF',
      secondary: '#76FF03',
      secondaryDark: '#64DD17',
      accent: '#E040FB',
      background: '#0A0F14',
      backgroundSecondary: '#111A22',
      surface: '#1A2530',
      surfaceElevated: '#22303F',
      text: '#E0F7FA',
      textSecondary: '#80DEEA',
      textMuted: '#37474F',
      textOnPrimary: '#003340',
      border: '#1A3A4A',
      divider: '#132630',
      error: '#FF5252',
      success: '#69F0AE',
      warning: '#FFD740',
      info: '#40C4FF',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 10. Pastel Dream
// ---------------------------------------------------------------------------
export const presetPastelDream: ThemeConfig = {
  name: 'Pastel Dream',
  colors: {
    light: {
      primary: '#B39DDB',
      primaryDark: '#9575CD',
      primaryLight: '#D1C4E9',
      secondary: '#F8BBD0',
      secondaryDark: '#F48FB1',
      accent: '#80CBC4',
      background: '#FDFBFF',
      backgroundSecondary: '#F3EFF8',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#2E2440',
      textSecondary: '#5E4B8A',
      textMuted: '#C5B8D9',
      textOnPrimary: '#FFFFFF',
      border: '#E0D6F0',
      divider: '#F0EAF8',
      error: '#E57373',
      success: '#81C784',
      warning: '#FFB74D',
      info: '#64B5F6',
    },
    dark: {
      primary: '#B39DDB',
      primaryDark: '#9575CD',
      primaryLight: '#D1C4E9',
      secondary: '#F8BBD0',
      secondaryDark: '#F48FB1',
      accent: '#80CBC4',
      background: '#181420',
      backgroundSecondary: '#221D2E',
      surface: '#2E2840',
      surfaceElevated: '#3A3350',
      text: '#EDE7F6',
      textSecondary: '#D1C4E9',
      textMuted: '#5E4B8A',
      textOnPrimary: '#FFFFFF',
      border: '#3D3460',
      divider: '#2E2650',
      error: '#EF9A9A',
      success: '#A5D6A7',
      warning: '#FFE082',
      info: '#90CAF9',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 11. Mint Fresh
// ---------------------------------------------------------------------------
export const presetMintFresh: ThemeConfig = {
  name: 'Mint Fresh',
  colors: {
    light: {
      primary: '#26A69A',
      primaryDark: '#00897B',
      primaryLight: '#80CBC4',
      secondary: '#66BB6A',
      secondaryDark: '#43A047',
      accent: '#00BFA5',
      background: '#F5FDFC',
      backgroundSecondary: '#E0F2F1',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#0D2B28',
      textSecondary: '#004D40',
      textMuted: '#80CBC4',
      textOnPrimary: '#FFFFFF',
      border: '#B2DFDB',
      divider: '#E0F2F1',
      error: '#D32F2F',
      success: '#2E7D32',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#4DB6AC',
      primaryDark: '#26A69A',
      primaryLight: '#80CBC4',
      secondary: '#81C784',
      secondaryDark: '#66BB6A',
      accent: '#1DE9B6',
      background: '#0C1B19',
      backgroundSecondary: '#14292A',
      surface: '#1E3A38',
      surfaceElevated: '#284A47',
      text: '#E0F2F1',
      textSecondary: '#80CBC4',
      textMuted: '#00695C',
      textOnPrimary: '#FFFFFF',
      border: '#1B4D46',
      divider: '#133B36',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};

// ---------------------------------------------------------------------------
// 12. Coral Reef
// ---------------------------------------------------------------------------
export const presetCoralReef: ThemeConfig = {
  name: 'Coral Reef',
  colors: {
    light: {
      primary: '#FF7043',
      primaryDark: '#E64A19',
      primaryLight: '#FF8A65',
      secondary: '#26C6DA',
      secondaryDark: '#0097A7',
      accent: '#FF5722',
      background: '#FFFAF8',
      backgroundSecondary: '#FBE9E7',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      text: '#2B1610',
      textSecondary: '#BF360C',
      textMuted: '#FFAB91',
      textOnPrimary: '#FFFFFF',
      border: '#FFCCBC',
      divider: '#FBE9E7',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      info: '#1976D2',
    },
    dark: {
      primary: '#FF8A65',
      primaryDark: '#FF7043',
      primaryLight: '#FFAB91',
      secondary: '#4DD0E1',
      secondaryDark: '#26C6DA',
      accent: '#FF6E40',
      background: '#1A100D',
      backgroundSecondary: '#2D1A14',
      surface: '#3E261E',
      surfaceElevated: '#4E3228',
      text: '#FBE9E7',
      textSecondary: '#FFAB91',
      textMuted: '#BF360C',
      textOnPrimary: '#FFFFFF',
      border: '#5D3427',
      divider: '#4E2A1F',
      error: '#EF5350',
      success: '#66BB6A',
      warning: '#FFA726',
      info: '#42A5F5',
    },
  },
  typography: defaultTypography,
  spacing: defaultSpacing,
  radius: defaultRadius,
  shadows: defaultShadows,
};
