import type { BodyPart, BodyPartConfig, Exercise } from './types';

// ── 部位設定 ──────────────────────────────────────────────────────────────────
export const BODY_PARTS: BodyPartConfig[] = [
  { id: 'chest',     label: '胸',   labelEn: 'Chest',     icon: 'barbell-outline',        exerciseCount: 8 },
  { id: 'back',      label: '背中', labelEn: 'Back',      icon: 'body-outline',           exerciseCount: 10 },
  { id: 'legs',      label: '脚',   labelEn: 'Legs',      icon: 'walk-outline',           exerciseCount: 9 },
  { id: 'shoulders', label: '肩',   labelEn: 'Shoulders', icon: 'fitness-outline',        exerciseCount: 6 },
  { id: 'arms',      label: '腕',   labelEn: 'Arms',      icon: 'hand-left-outline',      exerciseCount: 7 },
  { id: 'core',      label: '腹',   labelEn: 'Core',      icon: 'radio-button-on-outline', exerciseCount: 5 },
];

// ── 種目マスタ ────────────────────────────────────────────────────────────────
export const EXERCISES: Exercise[] = [
  // ── 胸（Chest）8種目 ──────────────────────────────────────────────────────
  {
    id: 'chest_001',
    name: 'ベンチプレス',
    nameEn: 'Bench Press',
    bodyPart: 'chest',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '胸・肩・上腕三頭筋',
  },
  {
    id: 'chest_002',
    name: 'ダンベルフライ',
    nameEn: 'Dumbbell Fly',
    bodyPart: 'chest',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '胸',
  },
  {
    id: 'chest_003',
    name: 'インクラインベンチ',
    nameEn: 'Incline Bench Press',
    bodyPart: 'chest',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '上部胸・肩',
  },
  {
    id: 'chest_004',
    name: 'ディップス',
    nameEn: 'Dips',
    bodyPart: 'chest',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '胸・上腕三頭筋',
  },
  {
    id: 'chest_005',
    name: 'ケーブルクロス',
    nameEn: 'Cable Crossover',
    bodyPart: 'chest',
    icon: 'git-compare-outline',
    equipment: 'ケーブル',
    muscleDetail: '胸',
  },
  {
    id: 'chest_006',
    name: 'プッシュアップ',
    nameEn: 'Push-up',
    bodyPart: 'chest',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '胸・肩・上腕三頭筋',
  },
  {
    id: 'chest_007',
    name: 'インクラインダンベルプレス',
    nameEn: 'Incline Dumbbell Press',
    bodyPart: 'chest',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '上部胸',
  },
  {
    id: 'chest_008',
    name: 'ペックデック',
    nameEn: 'Pec Deck',
    bodyPart: 'chest',
    icon: 'fitness-outline',
    equipment: 'マシン',
    muscleDetail: '胸',
  },

  // ── 背中（Back）10種目 ────────────────────────────────────────────────────
  {
    id: 'back_001',
    name: 'デッドリフト',
    nameEn: 'Deadlift',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '背中・臀部・腕',
  },
  {
    id: 'back_002',
    name: 'バーベルロウ',
    nameEn: 'Barbell Row',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '広背筋・僧帽筋',
  },
  {
    id: 'back_003',
    name: '懸垂',
    nameEn: 'Pull-up',
    bodyPart: 'back',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '背中・二頭筋・コア',
  },
  {
    id: 'back_004',
    name: 'ラットプルダウン',
    nameEn: 'Lat Pulldown',
    bodyPart: 'back',
    icon: 'git-compare-outline',
    equipment: 'ケーブル',
    muscleDetail: '広背筋',
  },
  {
    id: 'back_005',
    name: 'シーテッドロウ',
    nameEn: 'Seated Row',
    bodyPart: 'back',
    icon: 'fitness-outline',
    equipment: 'マシン',
    muscleDetail: '広背筋・僧帽筋',
  },
  {
    id: 'back_006',
    name: 'ダンベルロウ',
    nameEn: 'Dumbbell Row',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '広背筋',
  },
  {
    id: 'back_007',
    name: 'チンアップ',
    nameEn: 'Chin-up',
    bodyPart: 'back',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '広背筋・二頭筋',
  },
  {
    id: 'back_008',
    name: 'Tバーロウ',
    nameEn: 'T-Bar Row',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '広背筋・僧帽筋',
  },
  {
    id: 'back_009',
    name: 'シュラッグ',
    nameEn: 'Shrug',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '僧帽筋',
  },
  {
    id: 'back_010',
    name: 'プルオーバー',
    nameEn: 'Pullover',
    bodyPart: 'back',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '広背筋・胸',
  },

  // ── 脚（Legs）9種目 ──────────────────────────────────────────────────────
  {
    id: 'legs_001',
    name: 'スクワット',
    nameEn: 'Squat',
    bodyPart: 'legs',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '大腿四頭筋・臀部・ハムストリング',
  },
  {
    id: 'legs_002',
    name: 'レッグプレス',
    nameEn: 'Leg Press',
    bodyPart: 'legs',
    icon: 'fitness-outline',
    equipment: 'マシン',
    muscleDetail: '大腿四頭筋・臀部',
  },
  {
    id: 'legs_003',
    name: 'レッグカール',
    nameEn: 'Leg Curl',
    bodyPart: 'legs',
    icon: 'fitness-outline',
    equipment: 'マシン',
    muscleDetail: 'ハムストリング',
  },
  {
    id: 'legs_004',
    name: 'レッグエクステンション',
    nameEn: 'Leg Extension',
    bodyPart: 'legs',
    icon: 'fitness-outline',
    equipment: 'マシン',
    muscleDetail: '大腿四頭筋',
  },
  {
    id: 'legs_005',
    name: 'カーフレイズ',
    nameEn: 'Calf Raise',
    bodyPart: 'legs',
    icon: 'walk-outline',
    equipment: 'マシン',
    muscleDetail: '腓腹筋・ヒラメ筋',
  },
  {
    id: 'legs_006',
    name: 'ブルガリアンスクワット',
    nameEn: 'Bulgarian Split Squat',
    bodyPart: 'legs',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '大腿四頭筋・臀部',
  },
  {
    id: 'legs_007',
    name: 'ルーマニアンデッドリフト',
    nameEn: 'Romanian Deadlift',
    bodyPart: 'legs',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: 'ハムストリング・臀部',
  },
  {
    id: 'legs_008',
    name: 'ランジ',
    nameEn: 'Lunge',
    bodyPart: 'legs',
    icon: 'walk-outline',
    equipment: 'ダンベル',
    muscleDetail: '大腿四頭筋・臀部',
  },
  {
    id: 'legs_009',
    name: 'ヒップスラスト',
    nameEn: 'Hip Thrust',
    bodyPart: 'legs',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '臀部・ハムストリング',
  },

  // ── 肩（Shoulders）6種目 ─────────────────────────────────────────────────
  {
    id: 'shoulders_001',
    name: 'ショルダープレス',
    nameEn: 'Shoulder Press',
    bodyPart: 'shoulders',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '三角筋・上腕三頭筋',
  },
  {
    id: 'shoulders_002',
    name: 'サイドレイズ',
    nameEn: 'Lateral Raise',
    bodyPart: 'shoulders',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '三角筋（側面）',
  },
  {
    id: 'shoulders_003',
    name: 'フロントレイズ',
    nameEn: 'Front Raise',
    bodyPart: 'shoulders',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '三角筋（前面）',
  },
  {
    id: 'shoulders_004',
    name: 'フェイスプル',
    nameEn: 'Face Pull',
    bodyPart: 'shoulders',
    icon: 'git-compare-outline',
    equipment: 'ケーブル',
    muscleDetail: '三角筋（後面）・僧帽筋',
  },
  {
    id: 'shoulders_005',
    name: 'アップライトロウ',
    nameEn: 'Upright Row',
    bodyPart: 'shoulders',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '三角筋・僧帽筋',
  },
  {
    id: 'shoulders_006',
    name: 'アーノルドプレス',
    nameEn: 'Arnold Press',
    bodyPart: 'shoulders',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '三角筋（全面）',
  },

  // ── 腕（Arms）7種目 ──────────────────────────────────────────────────────
  {
    id: 'arms_001',
    name: 'バーベルカール',
    nameEn: 'Barbell Curl',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '上腕二頭筋',
  },
  {
    id: 'arms_002',
    name: 'トライセップスプッシュダウン',
    nameEn: 'Triceps Pushdown',
    bodyPart: 'arms',
    icon: 'git-compare-outline',
    equipment: 'ケーブル',
    muscleDetail: '上腕三頭筋',
  },
  {
    id: 'arms_003',
    name: 'ハンマーカール',
    nameEn: 'Hammer Curl',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '上腕二頭筋・腕橈骨筋',
  },
  {
    id: 'arms_004',
    name: 'スカルクラッシャー',
    nameEn: 'Skull Crusher',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'バーベル',
    muscleDetail: '上腕三頭筋',
  },
  {
    id: 'arms_005',
    name: 'チートカール',
    nameEn: 'Cheat Curl',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'ツール',
    muscleDetail: '上腕二頭筋',
  },
  {
    id: 'arms_006',
    name: 'インクラインカール',
    nameEn: 'Incline Curl',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '上腕二頭筋（長頭）',
  },
  {
    id: 'arms_007',
    name: 'トライセップスキックバック',
    nameEn: 'Triceps Kickback',
    bodyPart: 'arms',
    icon: 'barbell-outline',
    equipment: 'ダンベル',
    muscleDetail: '上腕三頭筋',
  },

  // ── 腹（Core）5種目 ──────────────────────────────────────────────────────
  {
    id: 'core_001',
    name: 'クランチ',
    nameEn: 'Crunch',
    bodyPart: 'core',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '腹直筋',
  },
  {
    id: 'core_002',
    name: 'プランク',
    nameEn: 'Plank',
    bodyPart: 'core',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: 'コア全体',
  },
  {
    id: 'core_003',
    name: 'レッグレイズ',
    nameEn: 'Leg Raise',
    bodyPart: 'core',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '腹直筋（下部）',
  },
  {
    id: 'core_004',
    name: 'ロールアウト',
    nameEn: 'Ab Rollout',
    bodyPart: 'core',
    icon: 'radio-button-on-outline',
    equipment: 'ローラー',
    muscleDetail: '腹直筋・コア',
  },
  {
    id: 'core_005',
    name: 'サイドクランチ',
    nameEn: 'Side Crunch',
    bodyPart: 'core',
    icon: 'body-outline',
    equipment: '自重',
    muscleDetail: '腹斜筋',
  },
];

// ── 部位別インデックス ──────────────────────────────────────────────────────
export const EXERCISES_BY_PART: Record<BodyPart, Exercise[]> = {
  chest:     EXERCISES.filter(e => e.bodyPart === 'chest'),
  back:      EXERCISES.filter(e => e.bodyPart === 'back'),
  legs:      EXERCISES.filter(e => e.bodyPart === 'legs'),
  shoulders: EXERCISES.filter(e => e.bodyPart === 'shoulders'),
  arms:      EXERCISES.filter(e => e.bodyPart === 'arms'),
  core:      EXERCISES.filter(e => e.bodyPart === 'core'),
};

// ── 日本語部位名 → BodyPart マッピング ──────────────────────────────────────
export const JP_TO_BODY_PART: Record<string, BodyPart> = {
  '胸':   'chest',
  '背中': 'back',
  '脚':   'legs',
  '肩':   'shoulders',
  '腕':   'arms',
  '腹':   'core',
};

// ── クイックスタートデフォルト5件 ────────────────────────────────────────
export const QUICK_START_IDS = [
  'chest_001', // ベンチプレス
  'legs_001',  // スクワット
  'back_001',  // デッドリフト
  'shoulders_001', // ショルダープレス
  'back_003',  // 懸垂
] as const;
